const database = require('./database')

// Initial Tables
async function createInitialTables(db) {

  // // await database.createTable(db, 'patient', `
  // //   pt1_patient_code UNIQUE PRIMARY KEY,
  // //   first_visit,
  // //   last_visit
  // // `)

  // await database.createTable(db, 'part1', `
  //   pt1_patient_record,
  //   pt1_patient_code UNIQUE PRIMARY KEY,
  //   pt1_first_name,
  //   pt1_last_name,
  //   pt1_age,
  //   pt1_city,
  //   pt1_date_diag,
  //   pt1_date_surgery,
  //   pt1_histo,
  //   pt1_gs,
  //   pt1_date_treatment,
  //   pt1_type_treatment,
  //   pt1_type_treatment_others,
  //   pt1_ecog_score,
  //   pt1_height,
  //   pt1_weight,
  //   pt1_bmi,
  //   pt1_bp,
  //   pt1_hr,
  //   pt1_pain_score,
  //   pt1_local_symps,
  //   pt1_sys_symps,
  //   pt1_psa,
  //   pt1_creatinine,
  //   pt1_wbc,
  //   pt1_rbc,
  //   pt1_hemoglobin,
  //   pt1_hematocrit,
  //   pt1_platelet,
  //   pt1_lactate,
  //   pt1_alkaline,
  //   pt1_ssb,
  //   pt1_salivary,
  //   pt1_renal,
  //   pt1_bone_scan,
  //   pt1_bone_withmetas,
  //   pt1_psma_picked,
  //   pt1_psma_prostate,
  //   pt1_psma_prostate_loc,
  //   pt1_psma_prostate_suv,
  //   pt1_psma_prostate_meas,
  //   pt1_psma_lymphs,
  //   pt1_psma_lymphs_loc,
  //   pt1_psma_lymphs_suv,
  //   pt1_psma_lymphs_meas,
  //   pt1_psma_bone,
  //   pt1_psma_bone_loc,
  //   pt1_psma_bone_suv,
  //   pt1_psma_bone_meas,
  //   pt1_psma_brain,
  //   pt1_psma_brain_loc,
  //   pt1_psma_brain_suv,
  //   pt1_psma_brain_meas,
  //   pt1_psma_lungs,
  //   pt1_psma_lungs_loc,
  //   pt1_psma_lungs_suv,
  //   pt1_psma_lungs_meas,
  //   pt1_psma_liver,
  //   pt1_psma_liver_loc,
  //   pt1_psma_liver_suv,
  //   pt1_psma_liver_meas,
  //   pt1_psma_others,
  //   pt1_psma_others_loc,
  //   pt1_psma_others_suv,
  //   pt1_psma_others_meas,
  //   pt1_fdg_prostate,
  //   pt1_fdg_prostate_loc,
  //   pt1_fdg_prostate_suv,
  //   pt1_fdg_prostate_meas,
  //   pt1_fdg_lymphs,
  //   pt1_fdg_lymphs_loc,
  //   pt1_fdg_lymphs_suv,
  //   pt1_fdg_lymphs_meas,
  //   pt1_fdg_bone,
  //   pt1_fdg_bone_loc,
  //   pt1_fdg_bone_suv,
  //   pt1_fdg_bone_meas,
  //   pt1_fdg_brain,
  //   pt1_fdg_brain_loc,
  //   pt1_fdg_brain_suv,
  //   pt1_fdg_brain_meas,
  //   pt1_fdg_lungs,
  //   pt1_fdg_lungs_loc,
  //   pt1_fdg_lungs_suv,
  //   pt1_fdg_lungs_meas,
  //   pt1_fdg_liver,
  //   pt1_fdg_liver_loc,
  //   pt1_fdg_liver_suv,
  //   pt1_fdg_liver_meas,
  //   pt1_fdg_others,
  //   pt1_fdg_others_loc,
  //   pt1_fdg_others_suv,
  //   pt1_fdg_others_meas,
  //   pt1_assessment,
  //   pt1_plan
  // `)

  // await database.createTable(db, 'part2', `
  //   therapy_session_id UNIQUE PRIMARY KEY,
  //   pt1_patient_record,
  //   pt1_patient_code,
  //   pt2_date_psma,
  //   pt2_premed,
  //   pt2_med,
  //   pt2_bp,
  //   pt2_hr,
  //   pt2_rr,
  //   pt2_o2,
  //   pt2_date_therapy,
  //   pt2_radiopharm,
  //   pt2_activity,
  //   pt2_fatigue,
  //   pt2_fatigue_text,
  //   pt2_nausea,
  //   pt2_nausea_text,
  //   pt2_dry_lips,
  //   pt2_dry_lips_text,
  //   pt2_headache,
  //   pt2_headache_text,
  //   pt2_bone_pain,
  //   pt2_bone_pain_text,
  //   pt2_others,
  //   pt2_others_text
  // `)
  
  // await database.createTable(db, 'part3', `
  //   post_therapy_session_id UNIQUE PRIMARY KEY,
  //   pt1_patient_record,
  //   pt1_patient_code,
  //   pt3_date_post_therapy,
  //   pt3_hour,
  //   pt3_spectct,
  //   pt3_prostate,
  //   pt3_prostate_text,
  //   pt3_lymph_nodes,
  //   pt3_lymph_nodes_text,
  //   pt3_bones,
  //   pt3_bones_text,
  //   pt3_lungs,
  //   pt3_lungs_text,
  //   pt3_liver,
  //   pt3_liver_text,
  //   pt3_sg,
  //   pt3_rk,
  //   pt3_lk
  // `)
  
  // await database.createTable(db, 'part4', `
  //   record_id UNIQUE PRIMARY KEY,
  //   pt1_patient_code,
  //   pt4_date,
  //   pt4_psa,
  //   pt4_creatinine,
  //   pt4_wbc,
  //   pt4_rbc,
  //   pt4_hemoglobin,
  //   pt4_hematocrit,
  //   pt4_platelet,
  //   pt4_lactate,
  //   pt4_alkaline,
  //   pt4_ssb,
  //   pt4_salivary,
  //   pt4_renal,
  //   pt4_bone_scan,
  //   pt4_bone_withmetas,
  //   pt4_psma_picked,
  //   pt4_psma_prostate,
  //   pt4_psma_prostate_loc,
  //   pt4_psma_prostate_suv,
  //   pt4_psma_prostate_meas,
  //   pt4_psma_lymphs,
  //   pt4_psma_lymphs_loc,
  //   pt4_psma_lymphs_suv,
  //   pt4_psma_lymphs_meas,
  //   pt4_psma_bone,
  //   pt4_psma_bone_loc,
  //   pt4_psma_bone_suv,
  //   pt4_psma_bone_meas,
  //   pt4_psma_brain,
  //   pt4_psma_brain_loc,
  //   pt4_psma_brain_suv,
  //   pt4_psma_brain_meas,
  //   pt4_psma_lungs,
  //   pt4_psma_lungs_loc,
  //   pt4_psma_lungs_suv,
  //   pt4_psma_lungs_meas,
  //   pt4_psma_liver,
  //   pt4_psma_liver_loc,
  //   pt4_psma_liver_suv,
  //   pt4_psma_liver_meas,
  //   pt4_psma_others,
  //   pt4_psma_others_loc,
  //   pt4_psma_others_suv,
  //   pt4_psma_others_meas,
  //   pt4_fdg_prostate,
  //   pt4_fdg_prostate_loc,
  //   pt4_fdg_prostate_suv,
  //   pt4_fdg_prostate_meas,
  //   pt4_fdg_lymphs,
  //   pt4_fdg_lymphs_loc,
  //   pt4_fdg_lymphs_suv,
  //   pt4_fdg_lymphs_meas,
  //   pt4_fdg_bone,
  //   pt4_fdg_bone_loc,
  //   pt4_fdg_bone_suv,
  //   pt4_fdg_bone_meas,
  //   pt4_fdg_brain,
  //   pt4_fdg_brain_loc,
  //   pt4_fdg_brain_suv,
  //   pt4_fdg_brain_meas,
  //   pt4_fdg_lungs,
  //   pt4_fdg_lungs_loc,
  //   pt4_fdg_lungs_suv,
  //   pt4_fdg_lungs_meas,
  //   pt4_fdg_liver,
  //   pt4_fdg_liver_loc,
  //   pt4_fdg_liver_suv,
  //   pt4_fdg_liver_meas,
  //   pt4_fdg_others,
  //   pt4_fdg_others_loc,
  //   pt4_fdg_others_suv,
  //   pt4_fdg_others_measure,
  //   pt4_assessment,
  //   pt4_plan
  // `)

}
// end Initial Tables

module.exports = {createInitialTables}
